"""Initial DB

Revision ID: 7cc88171c00c
Revises: 
Create Date: 2023-03-30 12:46:20.124689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc88171c00c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=8), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_git_version'))
    )
    op.create_table('query',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(length=4048), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query'))
    )
    op.create_table('request_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('git_version_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['git_version_id'], ['git_version.id'], name=op.f('fk_request_history_git_version_id_git_version')),
    sa.ForeignKeyConstraint(['query_id'], ['query.id'], name=op.f('fk_request_history_query_id_query')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_history')
    op.drop_table('query')
    op.drop_table('git_version')
    # ### end Alembic commands ###
